local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

local_production:
  service: Disk
  root: <%= Rails.root.join("storage_production") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY') %>
  region: <%= ENV.fetch('AWS_REGION') %>
  bucket: <%= ENV.fetch('S3_BUCKET_NAME') %>
